spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: puddyofficial1
    password: ${EMAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: wave
    password: ${DB_PASSWORD}


  redis:
    host: redis
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true


logging:
  level:
    root: INFO
    com.team.com.team.puddy: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO

springdoc:
  swagger-ui:
    enabled: true
    path: '/swagger-ui.html'
    try-it-out-enabled: false
  version: 'v1'

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET}

jwt:
  secret-key: ${JWT_SECRET}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


