spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


logging:
  level:
    org.hibernate.sql: debug

springdoc:
  swagger-ui:
    enabled: true
    path: '/swagger-ui.html'
    try-it-out-enabled: false
  version: 'v1'

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    stack:
      auto: false
    region:
      static: ${S3_REGION}
    s3:
      endpoint: ${S3_ENDPOINT}
      bucket: ${S3_BUCKET}

jwt:
  secret-key: 104f205379c2ff5cdfa3a61a1b5a860193072bbeebf6f90356595a81d6b752a2

